# Generated by Django 3.1 on 2021-03-18 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_favourite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
